version: '3'

services:
  bridging-magednode0:
    container_name: bridging-magednode0
    image: "warmagezone/localnetnode"
    ports:
      - "27656-27657:26656-26657"
      - "8645-8646:8545-8546"
      - "9190-9191:9090-9091"
      - "1417:1317"
    environment:
      - ID=0
      - LOG=${LOG:-maged.log}
    volumes:
      - ./build-bridging:/warmage:Z
    networks:
      bridging-localnet:
        ipv4_address: 192.168.11.2

  bridging-magednode1:
    container_name: bridging-magednode1
    image: "warmagezone/localnetnode"
    ports:
      - "27659-27660:26656-26657"
      - "8647-8648:8545-8546"
    environment:
      - ID=1
      - LOG=${LOG:-maged.log}
    volumes:
      - ./build-bridging:/warmage:Z
    networks:
      bridging-localnet:
        ipv4_address: 192.168.11.3

  bridging-magednode2:
    container_name: bridging-magednode2
    image: "warmagezone/localnetnode"
    environment:
      - ID=2
      - LOG=${LOG:-maged.log}
    ports:
      - "27661-27662:26656-26657"
      - "8649-8650:8545-8546"
    volumes:
      - ./build-bridging:/warmage:Z
    networks:
      bridging-localnet:
        ipv4_address: 192.168.11.4

  bridging-magednode3:
    container_name: bridging-magednode3
    image: "warmagezone/localnetnode"
    environment:
      - ID=3
      - LOG=${LOG:-maged.log}
    ports:
      - "27663-27664:26656-26657"
      - "8651-8652:8545-8546"
    volumes:
      - ./build-bridging:/warmage:Z
    networks:
      bridging-localnet:
        ipv4_address: 192.168.11.5

networks:
  bridging-localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.11.0/24
